Repository appsignal/diagnose_tests, pull requests merged in 2021-11, with the labels that each got.

#23 Submit diagnose reports to spec server
  Gemfile
  Gemfile.lock
  spec/diagnose_spec.rb
  spec/spec_helper.rb
  spec/support/diagnose_report_helper.rb
  spec/support/output_helper.rb
  spec/support/server.rb
Labels: enhancement

#25 Update diagnose specs to match Ruby gem format
  ruby/Gemfile.lock
  spec/diagnose_spec.rb
  spec/support/diagnose_report_helper.rb
  spec/support/runner.rb
Labels: chore

#27 Update Node.js config options
  spec/diagnose_spec.rb
Labels: enhancement

#26 Elixir diagnose specs updates
  spec/diagnose_spec.rb
  spec/support/runner.rb
Labels: chore

#28 Add ruby version file and thin server handler
  .ruby-version
  Gemfile
  Gemfile.lock
  spec/diagnose_spec.rb
Labels: bug

#30 Add test for query params in report transmission
  spec/diagnose_spec.rb
Labels: enhancement

#34 Test the report's "sources" sub-section
  bin/test
  elixir/config/config.exs
  ruby/config/appsignal.yml
  spec/diagnose_spec.rb
  spec/support/diagnose_report_helper.rb
  spec/support/server.rb
Labels: chore

#35 Expect params' `name` to be non-empty
  spec/diagnose_spec.rb
Labels: bug

#31 Test previously ignored lines
  spec/diagnose_spec.rb
  spec/support/runner.rb
Labels: chore

#36 Add Node.js sources to the diagnose report
  spec/diagnose_spec.rb
Labels: chore

#38 Fix Node.js sources environment and remove `log_path_file`
  spec/diagnose_spec.rb
  spec/support/runner.rb
Labels: chore

#39 Set config for development env
  ruby/config/appsignal.yml
Labels: bug

#37 Test Push API key validation
  spec/diagnose_spec.rb
  spec/spec_helper.rb
  spec/support/server.rb
Labels: enhancement

#40 Add integration path environment variables
  .gitignore
  bin/test-all
  elixir/mix.exs
  nodejs/.npmrc
  nodejs/package-lock.json
  ruby/Gemfile
  spec/support/runner.rb
Labels: dev happiness

#41 Update Ruby to test for filter_data_keys
  spec/diagnose_spec.rb
Labels: chore

#42 Match camel case config opts for Node.js
  spec/diagnose_spec.rb
Labels: enhancement

#43 Remove valid opt asserts for Elixir
  spec/diagnose_spec.rb
Labels: bug

#44 Add scenario for report submission failure
  ruby/Gemfile.lock
  spec/diagnose_spec.rb
  spec/support/server.rb
Labels: chore

#45 Remove filter_data_keys config option
  spec/diagnose_spec.rb
Labels: chore

#47 The Node.js apiKey option is renamed to pushApiKey
  spec/diagnose_spec.rb
Labels: chore

#48 Add system source to Node.js config sources
  spec/diagnose_spec.rb
Labels: chore

#46 Add requestHeaders config option to Node.js
  spec/diagnose_spec.rb
Labels: bug

#50 Remove default logPath option for Node.js
  spec/diagnose_spec.rb
Labels: chore

#49 Add env metadata config option to Node.js & Elixir
  spec/diagnose_spec.rb
Labels: chore
