Repository appsignal/diagnose_tests, pull requests merged in 2021-12, with the labels that each got.

#52 Order Ruby config opts alphabetically
  spec/diagnose_spec.rb
Labels: bug

#53 Update Git linter (Lintje) to 0.6.1
  script/lint_git
Labels: chore, dev happiness

#54 Revert log_level default config option
  spec/diagnose_spec.rb
Labels: bug

#55 Update default headers for Elixir
  spec/diagnose_spec.rb
Labels: chore
