Repository appsignal/diagnose_tests, pull requests merged in 2022-01, with the labels that each got.

#56 Add sendParams option for Node.js
  spec/diagnose_spec.rb
Labels: bug

#57 Add sendSessionData to Node.js tests
  spec/diagnose_spec.rb
Labels: bug

#58 Remove extension package from Node.js deps
  nodejs/package.json
  spec/support/runner.rb
Labels: enhancement

#59 Use send_session_data in Ruby gem tests
  spec/diagnose_spec.rb
Labels: chore

#60 Expect active to be false on Node.js
  spec/diagnose_spec.rb
Labels: bug

#61 Store Node.js install report in the ext dir
  spec/support/runner.rb
Labels: chore

#62 Add send_session_data to Elixir
  spec/diagnose_spec.rb
Labels: chore

#63 Add Elixir override config source
  spec/diagnose_spec.rb
Labels: chore
